# fly.toml app configuration file generated for food-identifier-app on 2025-04-13T17:05:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'food-identifier-app'
primary_region = 'dfw'

[build]
  command = "npm run build"
  dockerfile = "Dockerfile"

[build.args]
  NODE_ENV = "production"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node ./build/server.js"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
